<?php

namespace App\Support\Admission\Bridge;

class BridgeErrorCode
{
    public const BINDING_NOT_FOUND = 'BRIDGE_BINDING_NOT_FOUND';

    public const BINDING_INACTIVE = 'BRIDGE_BINDING_INACTIVE';

    public const BINDING_AMBIGUOUS = 'BRIDGE_BINDING_AMBIGUOUS';

    public const MAP_VERSION_MISMATCH = 'BRIDGE_MAP_VERSION_MISMATCH';

    public const MAP_INCOMPLETE = 'BRIDGE_MAP_INCOMPLETE';

    public const MAP_PROFILE_NOT_FOUND = 'BRIDGE_MAP_PROFILE_NOT_FOUND';

    public const MAP_VALIDATION_FAILED = 'BRIDGE_MAP_VALIDATION_FAILED';

    public const ORCHESTRATION_FAILED = 'BRIDGE_ORCHESTRATION_FAILED';

    public const DUPLICATE_POLICY_UNSUPPORTED = 'BRIDGE_DUPLICATE_POLICY_UNSUPPORTED';
}
