<?php

namespace App\Support\Dova;

/**
 * Canonical registry of Dova copilot actions.
 * Filtered by portal + role; boosted by page context.
 */
final class DovaActionCatalog
{
    /**
     * @return array<string, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            // —— Public website ——
            'open_admissions' => [
                'label' => ['en' => 'Open Admissions', 'ar' => 'فتح القبول والتسجيل'],
                'type' => 'anchor',
                'anchor' => '#visit',
                'icon' => 'bi-door-open',
                'portals' => ['public'],
                'roles' => ['guest'],
                'contexts' => ['home', 'admissions'],
                'keywords' => ['admission', 'admissions', 'apply', 'enroll', 'registration', 'قبول', 'تسجيل', 'التقديم'],
                'priority' => 100,
                'expression' => 'helping',
            ],
            'book_visit' => [
                'label' => ['en' => 'Book a Campus Visit', 'ar' => 'حجز زيارة للمدرسة'],
                'type' => 'anchor',
                'anchor' => '#visit',
                'icon' => 'bi-calendar-check',
                'portals' => ['public'],
                'roles' => ['guest'],
                'contexts' => ['home', 'admissions'],
                'keywords' => ['visit', 'campus', 'tour', 'زيارة', 'موعد'],
                'priority' => 95,
                'expression' => 'helping',
            ],
            'view_fee_structure' => [
                'label' => ['en' => 'View Fee Structure', 'ar' => 'عرض هيكل الرسوم'],
                'type' => 'anchor',
                'anchor' => '#admissions',
                'icon' => 'bi-cash-stack',
                'portals' => ['public', 'guardian'],
                'contexts' => ['home', 'admissions', 'wallet'],
                'keywords' => ['fee', 'fees', 'tuition', 'payment', 'رسوم', 'مصروفات', 'سداد'],
                'priority' => 90,
                'expression' => 'explaining',
            ],
            'contact_admissions' => [
                'label' => ['en' => 'Contact Admissions', 'ar' => 'التواصل مع القبول'],
                'type' => 'anchor',
                'anchor' => '#contact',
                'icon' => 'bi-envelope',
                'portals' => ['public'],
                'roles' => ['guest'],
                'contexts' => ['home'],
                'keywords' => ['contact', 'email', 'phone', 'تواصل', 'اتصال'],
                'priority' => 80,
                'expression' => 'helping',
            ],

            // —— Admin ——
            'admin_open_admissions' => [
                'label' => ['en' => 'Open Admissions Settings', 'ar' => 'إعدادات القبول'],
                'type' => 'route',
                'route' => 'admin.website.admissions',
                'icon' => 'bi-door-open',
                'portals' => ['admin'],
                'contexts' => ['website', 'admissions'],
                'keywords' => ['admission', 'admissions', 'قبول', 'تسجيل'],
                'priority' => 100,
                'expression' => 'explaining',
            ],
            'create_student' => [
                'label' => ['en' => 'Create New Student', 'ar' => 'إضافة طالب جديد'],
                'type' => 'route',
                'route' => 'admin.students.create',
                'icon' => 'bi-person-plus',
                'portals' => ['admin'],
                'contexts' => ['students'],
                'keywords' => ['create student', 'new student', 'add student', 'register student', 'طالب جديد', 'إضافة طالب', 'تسجيل طالب'],
                'priority' => 98,
                'expression' => 'helping',
            ],
            'students_list' => [
                'label' => ['en' => 'View Students', 'ar' => 'عرض الطلاب'],
                'type' => 'route',
                'route' => 'admin.students.index',
                'icon' => 'bi-people',
                'portals' => ['admin'],
                'contexts' => ['students'],
                'keywords' => ['students', 'student list', 'طلاب', 'قائمة الطلاب'],
                'priority' => 85,
                'expression' => 'explaining',
            ],
            'create_form' => [
                'label' => ['en' => 'Create Application Form', 'ar' => 'إنشاء نموذج تقديم'],
                'type' => 'route',
                'route' => 'admin.forms.create',
                'icon' => 'bi-file-earmark-plus',
                'portals' => ['admin'],
                'contexts' => ['forms'],
                'keywords' => ['form', 'application form', 'download form', 'نموذج', 'استمارة', 'تقديم'],
                'priority' => 92,
                'expression' => 'helping',
            ],
            'forms_list' => [
                'label' => ['en' => 'Manage Forms', 'ar' => 'إدارة النماذج'],
                'type' => 'route',
                'route' => 'admin.forms.index',
                'icon' => 'bi-ui-checks',
                'portals' => ['admin'],
                'contexts' => ['forms'],
                'keywords' => ['forms', 'submissions', 'نماذج', 'تقديمات'],
                'priority' => 80,
                'expression' => 'explaining',
            ],
            'attendance_dashboard' => [
                'label' => ['en' => 'Attendance Dashboard', 'ar' => 'لوحة الحضور'],
                'type' => 'route',
                'route' => 'admin.attendances.dashboard',
                'icon' => 'bi-clipboard-check',
                'portals' => ['admin'],
                'contexts' => ['attendance'],
                'keywords' => ['attendance', 'absence', 'present', 'حضور', 'غياب'],
                'priority' => 88,
                'expression' => 'explaining',
            ],
            'mark_attendance' => [
                'label' => ['en' => 'Mark Attendance', 'ar' => 'تسجيل الحضور'],
                'type' => 'route',
                'route' => 'admin.attendances.mark.form',
                'icon' => 'bi-check2-square',
                'portals' => ['admin'],
                'contexts' => ['attendance'],
                'keywords' => ['mark attendance', 'record attendance', 'تسجيل حضور'],
                'priority' => 86,
                'expression' => 'teaching',
            ],
            'attendance_reports' => [
                'label' => ['en' => 'Open Reports', 'ar' => 'فتح التقارير'],
                'type' => 'route',
                'route' => 'admin.timetable.daily-coverage.distribution-report',
                'icon' => 'bi-bar-chart',
                'portals' => ['admin'],
                'contexts' => ['attendance', 'timetable'],
                'keywords' => ['report', 'reports', 'analytics', 'تقرير', 'تقارير', 'إحصائيات'],
                'priority' => 84,
                'expression' => 'explaining',
            ],
            'website_cms' => [
                'label' => ['en' => 'Website CMS', 'ar' => 'إدارة الموقع'],
                'type' => 'route',
                'route' => 'admin.website.index',
                'icon' => 'bi-globe',
                'portals' => ['admin'],
                'contexts' => ['website'],
                'keywords' => ['website', 'cms', 'landing', 'موقع', 'صفحة'],
                'priority' => 75,
                'expression' => 'helping',
            ],
            'timetable' => [
                'label' => ['en' => 'Open Timetable', 'ar' => 'فتح الجدول الدراسي'],
                'type' => 'route',
                'route' => 'admin.timetable.edit',
                'icon' => 'bi-calendar3',
                'portals' => ['admin'],
                'contexts' => ['timetable'],
                'keywords' => ['timetable', 'schedule', 'جدول', 'حصص'],
                'priority' => 82,
                'expression' => 'explaining',
            ],

            // —— Teacher ——
            'teacher_attendance' => [
                'label' => ['en' => 'Class Attendance', 'ar' => 'حضور الحصة'],
                'type' => 'route',
                'route' => 'teacher.attendances.index',
                'icon' => 'bi-clipboard-check',
                'portals' => ['teacher'],
                'contexts' => ['attendance'],
                'keywords' => ['attendance', 'class', 'mark', 'حضور', 'حصة'],
                'priority' => 95,
                'expression' => 'teaching',
            ],
            'teacher_timetable' => [
                'label' => ['en' => 'My Timetable', 'ar' => 'جدولي الدراسي'],
                'type' => 'route',
                'route' => 'teacher.timetables.index',
                'icon' => 'bi-calendar3',
                'portals' => ['teacher'],
                'contexts' => ['timetable', 'teachers'],
                'keywords' => ['timetable', 'schedule', 'جدول'],
                'priority' => 90,
                'expression' => 'explaining',
            ],
            'teacher_live_streams' => [
                'label' => ['en' => 'Live Streams', 'ar' => 'البث المباشر'],
                'type' => 'route',
                'route' => 'teacher.live-streams.index',
                'icon' => 'bi-camera-video',
                'portals' => ['teacher'],
                'contexts' => ['live_streams'],
                'keywords' => ['live', 'stream', 'broadcast', 'بث', 'مباشر'],
                'priority' => 85,
                'expression' => 'helping',
            ],

            // —— Guardian ——
            'guardian_dashboard' => [
                'label' => ['en' => 'Parent Dashboard', 'ar' => 'لوحة ولي الأمر'],
                'type' => 'route',
                'route' => 'guardian.dashboard',
                'icon' => 'bi-house',
                'portals' => ['guardian'],
                'contexts' => ['dashboard'],
                'keywords' => ['dashboard', 'home', 'لوحة', 'الرئيسية'],
                'priority' => 100,
                'expression' => 'welcome',
            ],
            'guardian_attendance' => [
                'label' => ['en' => 'View Attendance', 'ar' => 'عرض الحضور'],
                'type' => 'route',
                'route' => 'guardian.dashboard',
                'icon' => 'bi-calendar-check',
                'portals' => ['guardian'],
                'contexts' => ['attendance'],
                'keywords' => ['attendance', 'absence', 'حضور', 'غياب'],
                'priority' => 95,
                'expression' => 'explaining',
            ],
            'guardian_grades' => [
                'label' => ['en' => 'View Grades', 'ar' => 'عرض الدرجات'],
                'type' => 'route',
                'route' => 'guardian.dashboard',
                'icon' => 'bi-mortarboard',
                'portals' => ['guardian'],
                'contexts' => ['grades'],
                'keywords' => ['grades', 'results', 'marks', 'درجات', 'نتائج'],
                'priority' => 93,
                'expression' => 'success',
            ],
            'guardian_wallet' => [
                'label' => ['en' => 'Fees & Wallet', 'ar' => 'الرسوم والمحفظة'],
                'type' => 'route',
                'route' => 'guardian.wallet',
                'icon' => 'bi-wallet2',
                'portals' => ['guardian'],
                'contexts' => ['wallet'],
                'keywords' => ['wallet', 'fees', 'payment', 'رسوم', 'محفظة', 'دفع'],
                'priority' => 90,
                'expression' => 'helping',
            ],

            // —— Student ——
            'student_dashboard' => [
                'label' => ['en' => 'My Dashboard', 'ar' => 'لوحتي'],
                'type' => 'route',
                'route' => 'student.dashboard',
                'icon' => 'bi-house',
                'portals' => ['student'],
                'contexts' => ['dashboard'],
                'keywords' => ['dashboard', 'home', 'لوحة'],
                'priority' => 100,
                'expression' => 'welcome',
            ],
            'student_live_streams' => [
                'label' => ['en' => 'My Live Classes', 'ar' => 'حصصي المباشرة'],
                'type' => 'route',
                'route' => 'student.live-streams.index',
                'icon' => 'bi-camera-video',
                'portals' => ['student'],
                'contexts' => ['live_streams'],
                'keywords' => ['live', 'class', 'stream', 'بث', 'حصة'],
                'priority' => 90,
                'expression' => 'helping',
            ],
        ];
    }
}
