<?php

return [
    'page_slug' => 'school-talent',

    'library' => [
        'hero' => ['label' => 'Hero', 'category' => 'core', 'anchor' => 'home'],
        'hero_stats' => ['label' => 'Hero Statistics (inside hero)', 'category' => 'core'],
        'trust' => ['label' => 'Trust Strip', 'category' => 'core'],
        'about' => ['label' => 'About School', 'category' => 'core', 'anchor' => 'about'],
        'stages' => ['label' => 'School Stages', 'category' => 'academics', 'anchor' => 'stages'],
        'why' => ['label' => 'Why School Talent', 'category' => 'academics', 'anchor' => 'why'],
        'student_life' => ['label' => 'Student Life', 'category' => 'life', 'anchor' => 'student-life'],
        'facilities' => ['label' => 'Facilities', 'category' => 'campus', 'anchor' => 'facilities'],
        'academics' => ['label' => 'Academic Programs', 'category' => 'academics', 'anchor' => 'academics'],
        'events' => ['label' => 'Events', 'category' => 'news', 'anchor' => 'events'],
        'news' => ['label' => 'News & Blog', 'category' => 'news', 'anchor' => 'news'],
        'gallery' => ['label' => 'Gallery', 'category' => 'media', 'anchor' => 'gallery'],
        'principal' => ['label' => 'Principal Message', 'category' => 'core'],
        'achievements' => ['label' => 'Achievements', 'category' => 'highlights'],
        'success_stories' => ['label' => 'Success Stories', 'category' => 'highlights'],
        'testimonials' => ['label' => 'Testimonials', 'category' => 'community'],
        'parent_trust' => ['label' => 'Parent Trust Band', 'category' => 'community'],
        'admissions' => ['label' => 'Admissions', 'category' => 'conversion', 'anchor' => 'admissions'],
        'careers' => ['label' => 'Become a Teacher / Careers', 'category' => 'conversion'],
        'blog_anchor' => ['label' => 'Blog Anchor', 'category' => 'news', 'anchor' => 'blog'],
        'partners' => ['label' => 'Partners & Accreditations', 'category' => 'trust'],
        'faq' => ['label' => 'FAQ', 'category' => 'support', 'anchor' => 'faq'],
        'contact' => ['label' => 'Contact', 'category' => 'support', 'anchor' => 'contact'],
        'final_cta' => ['label' => 'Final CTA', 'category' => 'conversion'],
        'custom' => ['label' => 'Custom Section', 'category' => 'custom', 'custom' => true],
    ],

    'custom_subtypes' => [
        'text_block' => 'Text Block',
        'image_block' => 'Image Block',
        'gallery' => 'Gallery',
        'video' => 'Video',
        'cta_banner' => 'CTA Banner',
        'statistics' => 'Statistics',
        'cards_grid' => 'Cards Grid',
        'accordion' => 'Accordion',
        'faq' => 'FAQ',
        'rich_content' => 'Rich Content',
    ],

    'default_settings' => [
        'title' => null,
        'subtitle' => null,
        'eyebrow' => null,
        'background_color' => null,
        'background_image_media_id' => null,
        'background_image_url' => null,
        'padding_top' => null,
        'padding_bottom' => null,
        'section_class' => null,
        'animation' => 'reveal',
        'ctas' => [],
    ],
];
